name: generate animation

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:

      - name: generate-snake-game-from-github-contribution-grid
      # You may pin to the exact commit or the version.
      # uses: Platane/snk@aebc3a92857730857d5a96010a3538f16bbec662
        uses: Platane/snk@v3.0.0
        with:
          # github user name
          github_user_name: ${{ github.repository_owner }}
        # list of files to generate.
        #one file per line. Each output can be customized with options as query string.
    
        #  supported query string options:
    
        #  - palette:      A preset of color, one of [github, github-dark, github-light]
        #  - color_snake:  Color of the snake
        #  - color_dots:   Coma separated list of dots color. 
        #                The first one is 0 contribution, then it goes from the low contribution to the highest.
        #                Exactly 5 colors are expected.
    
          outputs: |
            dark.svg?palette=github-dark&color_snake=blue
            light.svg?color_snake=#7845ab
            ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
